In [1]:
import numpy as np #ввод
import random 
m=[1,-1] 
v=0
n=int(input())
a=np.zeros((n,n))
for i in range(n):
    for j in range(n):
        a[i,j]=random.choice(m)
print(a)
for i in range(n):
    for j in range(n):
        v+=a[i,j]*a[i,j-1]
        v+=a[i-1,j]*a[i,j]        
print(v)

10
[[-1. -1. -1.  1.  1.  1. -1.  1.  1.  1.]
 [ 1. -1.  1. -1.  1.  1.  1. -1.  1. -1.]
 [ 1. -1.  1.  1. -1.  1. -1. -1. -1.  1.]
 [-1. -1.  1.  1. -1. -1.  1. -1. -1. -1.]
 [ 1.  1. -1. -1. -1. -1.  1.  1. -1. -1.]
 [-1.  1. -1.  1.  1. -1. -1. -1. -1.  1.]
 [ 1. -1.  1. -1.  1. -1. -1.  1. -1. -1.]
 [ 1.  1. -1. -1.  1. -1.  1.  1. -1.  1.]
 [ 1. -1. -1. -1.  1. -1. -1. -1.  1. -1.]
 [-1. -1. -1.  1.  1. -1. -1.  1. -1.  1.]]
-12.0
